### ISSUE TITLE
[BUG] BGAs not playing, being overwritten by RandomMovies

### ISSUE THREAD

**Issue by MrTwinkles47** [TeamRizu/OutFox#513] opened 2022-03-29 02:31 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues and none matched.

### Operating System

Windows 10

### CPU

Intel i3 (3rd-gen)

### GPU

GTX 660

### Storage

SSD

### Game Version

4.14.1

### Game Mode

dance

### Theme

Simply Love 5.1.1

### Describe the problem

Background videos are not showing when they should. Game fallsback to playing RandomMovies.

Within a ~1.5 hour play session, ~1/10th of the BGAs did not play. Log shows a `FFMPEG Decoder: AVFormat Error` whether the video worked or didn't.

Things I've tried or observed:
1. Built new song cache files -> problem still exists
2. Cache files no longer have BG/FGCHANGES tags
3. Video files do exist and are specified in the sm/ssc files

### Describe what should happen

Videos or other media specified in the `#BGCHANGES` tag should work.

### Relevant Log output

[log.txt](https://github.com/TeamRizu/OutFox/files/8367581/log.txt)

**Comment by Jousway** [comment] 2022-03-29 17:44
AVFormat error has nothing to do with it, its trying to open the file in the old way and if it cant it does the AVIO fallback which works fine, the issue is for some reason its overwriting the BGA info with random movies when they are active cuz the old pre-cache rewrite system has a does video exist check thats failing because I rewrote the entire cache system cuz it was utter garbage, just need to fix a check

**Comment by Scraticus** [comment] 2022-05-24 21:48
Fixed in 4.15

**Closed by Scraticus** 2022-05-24 21:48 UTC
Labels: BUG
