### ISSUE TITLE
Crashed when I pulled the USB dongle

### ISSUE THREAD

**Issue by TakeWalker** [TeamRizu/OutFox#7] opened 2020-06-10 19:44 UTC
Sometimes have issues with my headphones not connecting back up to the computer after being away from it. Pulling the dongle and reinserting it is the usual fix. Also made Stepmania instantly crash.
[log.txt](https://github.com/TeamRizu/OutFox/files/4760806/log.txt)

**Comment by Scraticus** [comment] 2020-06-13 08:26
This is caused by the fact the game has no support for 'hotplugging' sound drivers. When we get round to the rewrite, this will be resolved. Will leave open until then.

**Comment by Scraticus** [comment] 2020-08-03 16:41
I'm gonna close this as it's an operating system issue, which will be fixed in alpha 5.0

**Closed by Scraticus** 2020-08-03 16:41 UTC
Labels: bug, investigating, sound, upstream bug, windows
