### ISSUE TITLE
[BUG] Freeze Arrows not saving in the editor

### ISSUE THREAD

**Issue by Beniplex** [TeamRizu/OutFox#453] opened 2021-11-05 16:35 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues and none matched.

### Operating System

Windows 10

### GPU

RTX 3080

### Storage

4TB SSD

### Game Version

4.10.0

### Describe the problem

In the latest version of OutFox I've been having a problem with the editor not saving certain notes, and I've gotten to a point I can replicate it.

Freeze arrows will not actually save and will vanish on reload / not load at all in game.

The most common way this occurs is when I delete a section of steps that begin on the tail end of a freeze arrow, but it also occurs when I copy/paste sections that include freeze arrows. They're not fakes, I turn on autoplay and assist tick and they're real, but they just don't save, and this is particularly annoying as I then have to be extra thorough in playtesting, especially on the lower levels.

https://www.youtube.com/watch?v=ZgGBi8Omx8w

YouTube video of me showing off the bug in the editor.

### Describe what should happen

Freeze Arrows should just save!

### Relevant Log output

[info.txt](https://github.com/TeamRizu/OutFox/files/7487518/info.txt)
[log.txt](https://github.com/TeamRizu/OutFox/files/7487519/log.txt)

**Comment by JoseVarelaP** [comment] 2021-11-05 20:11
Verified the cause. When using the Cut option, it begins checking for the notes to move over and clear to keep in the clipboard, and it seems that it's converting the tail of the hold into a note of some kind. This can be seen when using AutoPlay to run thorugh the whole hold and seeing the flash result. I'm currently looking into a fix for this situation.

https://user-images.githubusercontent.com/23246027/140572545-1fe734f9-51d2-4f34-986f-fa217cb92efa.mp4

**Closed** 2021-11-05 21:38 UTC
Labels: BUG, Good First Issue, Edit Mode

**Comment by JoseVarelaP** [comment] 2021-11-05 21:40
Fixed the problem, now the tail can remain after cutting.

https://user-images.githubusercontent.com/23246027/140581709-35ee01b3-60a0-4ad7-9afe-421eaa36ea9b.mp4
