### ISSUE TITLE
[Unexpected Behavior] "Double" default style when 2 people are present

### ISSUE THREAD

**Issue by JapanYoshi** [TeamRizu/OutFox#98] opened 2020-09-10 02:14 UTC
**What you're using**

Default theme for SM5.3. Started game with 2 players.

"Double" is the default selected option, despite it being a 1-player option.

**Expected behavior**

"Versus" should be the default selected option, because it is the first 2-player option.

**Comment by JoseVarelaP** [comment] 2020-09-10 02:34
This issue is a duplicate of #47 .

**Closed** 2021-03-07 01:31 UTC
Labels: Duplicate, Gameplay
