### ISSUE TITLE
[BUG] TimingWindowScale in Preferences.ini suspectedly broken

### ISSUE THREAD

**Issue by pucgenie** [TeamRizu/OutFox#138] opened 2020-10-28 20:10 UTC
OS: Windows 10 Pro Version 20H2 (OS Build 19042.608 - insider slow ring)
CPU: Intel(R) Core(tm) i7-7700HQ
RAM: more than 10GB free
GPU: NVIDIA GeForce GTX 1060 mobile
(Primary display: 120 Hz FullHD (Laptop))
Secondary display: 75 Hz FullHD (DisplayPort) - game uses exclusive fullscreen mode on that screen.
Storage: game stored on SSHD 678GB NTFS, 54GB free, 16KiB allocation unit size. System on NVMe SSD.

StepMania Version: StepMania 5.3 Outfox Alpha date-20201007 (in-game: Alpha 4.9)
Theme: default

**Describe the problem**

If using TimingWindowScale=0.840000 after about half a minute most steps get MISSed, after a few more seconds, all steps get missed, regardless of input device (gamepad, keyboard).
Reproducible every time, e.g. using the song "MechaTribe Assault", Hallway, M700 . It doesn't matter if playing in windowed mode or exclusive fullscreen mode.

**Describe what should happen**

It should not be impossible to hit steps at the right moment. It was working correctly in StepMania 5.3 Outfox Alpha date-20200619 before.
The default TimingWindowScale=1.000000 works.

**Logs and Additional context**

[info.txt](https://github.com/TeamRizu/OutFox/files/5454551/info.txt)
[log.txt](https://github.com/TeamRizu/OutFox/files/5454552/log.txt)
[userlog.txt](https://github.com/TeamRizu/OutFox/files/5454553/userlog.txt)
timelog.txt 0 bytes.

May be a regression caused while fixing https://github.com/TeamRizu/OutFox/issues/81 ?

**Comment by JoseVarelaP** [comment] 2020-10-28 20:42
This is a known bug that was fixed for the new release that will come soon. It was due to a bug that made the timing window scale itself, making it override and becoming even bigger. And yeah, it was a regression but it was also taken care of.

**Comment by Scraticus** [comment] 2020-10-30 16:34
Fixed in 4.9.1

**Closed by Scraticus** 2020-10-30 16:34 UTC
Labels: Input, Lua, Solved!
