### ISSUE TITLE
[BUG] Songs that start with a "." do not play audio on Linux

### ISSUE THREAD

**Issue by AED-001** [TeamRizu/OutFox#447] opened 2021-10-20 16:39 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues and none matched.

### Operating System

Xubuntu 21.04

### CPU

i9-9900K

### GPU

AMD Radeon RX 6800

### Game Version

4.10.0

### Describe the problem

Songs that start with a period do not play audio on Linux.

Example; .59 from DDR 4thMIX

It seems that the directory .59 is read, and so are the rest of the files in the directory (which is why it seems to scan successfully). 

The .ogg file .59 seems to not be read by whatever is interpreting it in OutFox. My guess is it is because it is classified as a hidden file/directory in Linux because it starts with a period.

![Screenshot_2021-10-20_12-36-42](https://user-images.githubusercontent.com/12076835/138134612-7afee70f-193e-4785-b0e6-05290e1dae01.png)

### Describe what should happen

The song should have audio.

### Relevant Log output

[info.txt](https://github.com/TeamRizu/OutFox/files/7382931/info.txt)

[log.txt](https://github.com/TeamRizu/OutFox/files/7382932/log.txt)

[userlog.txt](https://github.com/TeamRizu/OutFox/files/7382935/userlog.txt)

**Comment by jpdown** [comment] 2021-11-05 23:18
I can confirm this issue happening with two songs from the Animal Crossover pack:
* K.K. House (TAK Remix)
* K.K Cruisin' (Camellia Remix)

Perhaps the issue is songs containing a "."?
Interestingly, these two songs play preview audio in song select, but do not play audio in game.

**OS:** Arch Linux  
**CPU:** Ryzen 7 2700x  
**GPU:** NVIDIA GTX 1070Ti  
**Game Version:** OutFox 5.3.0 Alpha 4.10.0

Relevant logs:  
[info.txt](https://github.com/TeamRizu/OutFox/files/7489278/info.txt)
[log.txt](https://github.com/TeamRizu/OutFox/files/7489279/log.txt)
[userlog.txt](https://github.com/TeamRizu/OutFox/files/7489280/userlog.txt)

**Comment by aryoadhi** [comment] 2021-11-05 23:28
That couldn't be the case. The way of hidden files in Linux works is only by appending `.` symbol as the prefix, so:

- `file.mp3` is a normal file,
- `.file.mp3` is a hidden file.

Interesting enough we have multiple different case. Just for curious, I will try on Ubuntu Live USB instead of installation later, because I just nuked my Ubuntu install.

It may not be the cache issue, since my last test is spontanteous; I never have any song folders and files starting with `.` symbol on it.

**Comment by jpdown** [comment] 2021-11-05 23:53
I did a bit more testing and the issue appears to be whether the path contains any "." in it. For the following examples, I changed the folder name, the .ogg file name, and updated the `MUSIC` field in both the .sm and .ssc files. It's worth noting that `Songs` is relative to `/home/jaden/Games/OutFox-5.3.0-alpha-4.10.0-amd64-date-20211001/`.

* `Songs/Animal Crossover/K.K Cruisin' (Camellia Remix)/K.K. Cruisin' (Camellia Remix).ogg` - Does not work
* `Songs/Animal Crossover/K.K Cruisin' (Camellia Remix)/KK Cruisin' (Camellia Remix).ogg`- Does not work
* `Songs/Animal Crossover/KK Cruisin' (Camellia Remix)/K.K. Cruisin' (Camellia Remix).ogg`- Does not work
* `Songs/Animal Crossover/KK Cruisin' (Camellia Remix)/KK Cruisin' (Camellia Remix).ogg` - Works

The same pattern applied for K.K. House (TAK Remix). In all cases, preview audio works, but only when there are no "." does in game audio work. Also note that these paths do not start with ".", so it is not a hidden file issue.

**Comment by MrThatKid** [comment] 2021-11-06 00:03
So, I believe I've fixed this issue. It was a small logic error.
The general crux was if the file or path segment had a `.` as the first or second character (or if it was 1-2 characters long), the segment gets ignored.
This should no longer be an issue when the next release happens. I'll keep it open for now until the next alpha build launches.

**Comment by Scraticus** [comment] 2022-01-01 02:39
can you try the new 4.12 alpha and let us know if this is resolved?

**Comment by Scraticus** [comment] 2022-01-18 02:53
This was fixed in the previous alpha, 4.12, if you have any other issues, please reopen this issue

**Closed by Scraticus** 2022-01-18 02:53 UTC
Labels: BUG, Awaiting Answer From Reporter
